<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
    'Sabre\\Xml\\' => [$vendorDir . '/sabre/xml/lib'],
    'Sabre\\VObject\\' => [$vendorDir . '/sabre/vobject/lib'],
    'Sabre\\Uri\\' => [$vendorDir . '/sabre/uri/lib'],
    'Sabre\\HTTP\\' => [$vendorDir . '/sabre/http/lib'],
    'Sabre\\Event\\' => [$vendorDir . '/sabre/event/lib'],
    'Sabre\\DAV\\' => [$vendorDir . '/sabre/dav/lib/DAV'],
    'Sabre\\DAVACL\\' => [$vendorDir . '/sabre/dav/lib/DAVACL'],
    'Sabre\\CardDAV\\' => [$vendorDir . '/sabre/dav/lib/CardDAV'],
    'Sabre\\CalDAV\\' => [$vendorDir . '/sabre/dav/lib/CalDAV'],
    'Psr\\Log\\' => [$vendorDir . '/psr/log/Psr/Log'],
];
